### ISSUE TITLE
Use collision_monitor to stop motion

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_gazebo_plugins#16]
If we want to keep behavior consistent, when this node is used on hardware, we might want to add a subscriber to `state_valid` here as well and mimic the "e-stop" behavior" (see https://github.com/ros-simulation/gazebo_ros_pkgs/pull/283)

**Comment by mathias-luedtke** [comment]
Perhaps we should try again to merge our changes back..
https://github.com/ros-simulation/gazebo_ros_pkgs/pull/283 has its logic inverted..
Our collision monitor sends `true` if everything is fine (high level means okay in safety devices), but the gazebo plugin would stop in this case.
(so we need a topic_tools transform in between)

**Comment by fmessmer** [comment]
estop behavior is added in #22

**Comment by fmessmer** [comment]
state_valid behavior is added in #23 
@ipa-mdl FYI

**Comment by fmessmer** [comment]
both behaviors are available now
